apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: treetracker-web-map-client-mapping-next
  namespace: webmap
spec:
  hostname: next-dev.treetracker.org
  prefix: /
  service: treetracker-web-map-client-svc-next
  timeout_ms: 0
  precedence: 9
